tweets/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'tweets.views',
    url(r'^create/', 'create', name='create'),
)

twitter/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'twitter.views.home', name='home'),

    # Includes to other apps
    url(r'^user/', include('users.urls', namespace='users')),
    url(r'^tweets/', include('tweets.urls', namespace='tweets')),
    url(r'^admin/', include(admin.site.urls)),
)

users/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^register/', 'users.views.register', name='register'),
    url(r'^settings/', 'users.views.settings', name='settings'),
    url(r'^login/', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^logout/', 'django.contrib.auth.views.logout', {'next_page': 'home'}),
    url(r'^delete/', 'users.views.delete', name='delete'),
    url(r'^people/', 'users.views.people', name='people'),
    url(r'^profile/(?P<username>[\w.@+-]+)/$', 'users.views.profile', name='profile'),
    url(r'^follow/(?P<username>[\w.@+-]+)/$', 'users.views.follow', name='follow'),
    url(r'^unfollow/(?P<username>[\w.@+-]+)/$', 'users.views.unfollow', name='unfollow'),
    url(r'^password/done/', 'django.contrib.auth.views.password_change_done',
        {'template_name': 'change_password_done.html'}),
    url(r'^password/', 'django.contrib.auth.views.password_change',
        {'template_name': 'change_password.html',
         'post_change_redirect': 'users:django.contrib.auth.views.password_change_done'}),
)

tweets/models.py
from django.db import models
from django.utils import timezone


class Tweet(models.Model):
    user = models.ForeignKey('users.TwitterUser')
    content = models.CharField(max_length='140')
    created_at = models.DateTimeField(default=timezone.now())
    is_active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.content

    def get_mentioned_usernames(self):
        # TODO: change to something in which order is preserved? Set or Tuple or something?
        return [mention for mention in self.content.split() if mention.startswith('@')]


class Mention(models.Model):
    tweet = models.ForeignKey('Tweet')
    order_number = models.PositiveIntegerField()
    user = models.ForeignKey('users.TwitterUser', null=True)

templates/change_password.html
<h1>Change Password</h1>
<form method="post" action="{% url 'users:django.contrib.auth.views.password_change'%}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Change">
</form>

templates/change_password_done.html
<h1>Password Changed</h1>
Click <a href="{% url 'users:settings' %}">here</a> to go back to the settings page.

templates/create.html
<h1>Create Tweet</h1>
<hr/>
<form action="{% url 'tweets:create' %}" method="post">
    {% csrf_token %}
    {{ tweet_form.as_p }}
    <input type="submit" value="Tweet!">
</form>

templates/delete.html
<h1>Delete User</h1>
<p>This cannot be reversed. Are you sure?</p>
<form action="{% url 'users:delete' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes!"/>
</form>
<p><a href="{% url 'users:settings' %}">No!</a></p>

templates/feed.html
{% load mentions %}

<h1>Feed</h1>
<hr/>
<h2>Logged In: {{ user.email }}!</h2>
<a href="{% url 'users:django.contrib.auth.views.logout' %}">Logout</a><br/>
<a href="{% url 'users:settings' %}">Settings</a><br/>
<a href="{% url 'users:people' %}">People</a><br/>
<hr/>
<h2>Create a new tweet!</h2>
<form action="{% url 'tweets:create' %}" method="post">
    {% csrf_token %}
    {{ tweet_form.as_p }}
    <input type="submit" value="Tweet!">
</form>
<hr/>
<h2>Your Tweets</h2>
{% for tweet in user.tweet_set.all %}
    {{ tweet|linked_tweet|safe }}
    <p><strong>Created At:</strong> {{ tweet.created_at }}</p>
    <hr/>
{% endfor %}

templates/home.html
<h1>Homepage</h1>
<hr/>
<h2>Register Here</h2>
<form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
    {{ register_form.as_p }}
    <input type="submit" value="Register">
</form>
<hr/>
<h2>Login Here</h2>
<form action="{% url 'users:django.contrib.auth.views.login' %}" method="post">
    {% csrf_token %}
    {{ auth_form.as_p }}
    <input type="hidden" name="next" value="{{ next }}">
    <input type="submit" value="Login">
</form>

templates/login.html
<h1>Login</h1>
<hr/>
<form action="{% url 'users:django.contrib.auth.views.login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}">
    <input type="submit" value="Login">
</form>

templates/people.html
<h2>Following ({{ user.following.count }}):</h2>
{% for item in user.following.all %}
    <p><a href="{% url 'users:profile' item.followed.username %}">{{ item.followed.username }}</a></p>
{% endfor %}

<h2>Followed By ({{ user.being_followed_by.count }}):</h2>
{% for item in user.being_followed_by.all %}
    <p><a href="{% url 'users:profile' item.followed_by.username %}">{{ item.followed_by.username }}</a></p>
{% endfor %}

templates/profile.html
<h1>Profile Page</h1>

<p><strong>Username:</strong> {{ profile_user.username }}</p>
<p><strong>Email:</strong> {{ profile_user.email }}</p>
<p><strong>Name:</strong> {{ profile_user.get_full_name }}</p>
<p><strong>One Liner:</strong> {{ profile_user.one_liner }}</p>

<hr/>
{% if not self_profile %}
    {% if following %}
        <p>
        <form action="{% url 'users:unfollow' profile_user.username %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Unfollow"/>
        </form>
        </p>
    {% else %}
        <p>
        <form action="{% url 'users:follow' profile_user.username %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Follow"/>
        </form>
        </p>
    {% endif %}
    {% if followed_by %}
        <p>{{ profile_user.username }} follows you</p>
    {% endif %}
    <hr/>
{% endif %}

{% if user.is_authenticated %}
    Logged-in user: {{ user.username }}
{% endif %}

templates/register.html
<h1>Registration</h1>
<hr/>
<form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
    {{ register_form.as_p }}
    <input type="submit" value="Register">
</form>

templates/settings.html
<h1>Settings</h1>
<form action="{% url 'users:settings' %}" method="post">
    {% csrf_token %}
    {{ settings_form.as_p }}
    <input type="submit" value="Save">
</form>
<hr/>
<a href="{% url 'users:django.contrib.auth.views.password_change' %}">Change Password</a>
<hr/>
<a href="{% url 'users:delete' %}">Delete Account</a>
<hr/>
Back to <a href="{% url 'home' %}">home</a>